"""add autogenerate-Vote

Revision ID: 5becef96b8e3
Revises: 03674fde03c2
Create Date: 2023-08-21 16:49:24.333643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '5becef96b8e3'
down_revision: Union[str, None] = '03674fde03c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('create_at', sa.DATETIME(timezone=True), server_default=sa.text('GETDATE()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('create_at', sa.DATETIME(timezone=True), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_table('Post')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__User__3213E83FE57D47B3')
    )
    op.create_table('Post',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('published', mssql.BIT(), server_default=sa.text("('TRUE')"), autoincrement=False, nullable=False),
    sa.Column('create_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], name='Post_User_foreingKey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__Post__3213E83FCFA0C82E')
    )
    op.drop_table('votes')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
